env:
  global:
    - PATH: /usr/local/texlive/bin/x86_64-linux:$PATH
    - GH_REF: github.com/${TRAVIS_REPO_SLUG}.git
    - secure: "N0JlfjkDLdSzyLCc0qoW6oVQy3rhTPPh4WMkRno0I9LIfPF3RtVBIk/gqM4h0t2Kxe2hBkualue8MtLfwRqHNgeXbWbvRN77Tp9N4FJXb39bA0uISIfdzF8K3P7Tpm7Ch/8JgnMkRn3j5i4FjhSndgm4BLZ48Y36UBQxRz+pGhw="
before_script:
  - cd ./developers/ && sudo -E ./texlive_install.sh && cd ../
script: make
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then bash ./developers/deploy-ghpages.sh; fi
